### ISSUE TITLE
Support deployment with PVCs

### ISSUE THREAD

**Issue by craig-willis** [nds-org/workbench-helm-chart#6]
With https://github.com/nds-org/ndslabs/pull/261 merged, we need to update the Helm chart to use PVCs.  We have an open question about how to support our in-Pod etcd, since there is a known problem on NFS and NFS is our preferred provisioner for OpenStack.  

For now:
* etcd should use a PVC if the cloud provider offers a default provisioner
* etcd should use hostPath with pod pinned to a node for OpenStack

**Comment by bodom0015** [comment]
We deploy a default StorageClass on OpenStack, so a default should always be set. With the move to etcd3.3 and the ability to now use a PVC of the default storage class.

Closing this issue unless further work is needed here
